import librosa as libr


TRAIN_PROCESSED_DIR = '../train_data_proc'
TEST_PROCESSED_DIR = '../test_data_proc'

MIN_MIDI = 21 # A0
MAX_MIDI = 108 # C8
BINS_P_OCTAVE_MULT = 3
BINS_P_OCTAVE = BINS_P_OCTAVE_MULT * 12
FMIN = libr.midi_to_hz(MIN_MIDI)
N_BINS = (MAX_MIDI - MIN_MIDI + 1) * BINS_P_OCTAVE_MULT

CONTEXT_WINDOW_SIZE = 7
SEQUENCE_SIZE = 100
FREQUENCIES_SIZE = N_BINS
BATCH_SIZE = 64
EPOCHS = 1

INFERED_NOTE_N = 88
